### ISSUE TITLE
Pas possible de mettre les batiments devant le mouton avec le z index

### ISSUE THREAD

**Issue by astonedf** [AnteJR/UNIL-GameJam#12]
Les assets bâtiments cachent les entités comme les deux sont des enfants de l'objet background mais le mouton reste devant peu importe le z index

**Comment by AnteJR** [comment]
J'essaie un truc

**Comment by AnteJR** [comment]
J'ai essayé :

1. Mettre l'objet player comme un enfant de background ;
2. Ajouter l'objet player avec une fonction, comme les background ;
3. Ajouter l'objet player avec la command spawn, [comme dans l'exemple ici](https://kaboomjs.com/play?example=spriteatlas), mais j'ai une erreur indiquant que spawn n'est pas une fonction (ou alors c'est dépendant d'un objet "level", mais je ne trouve pas de trace de cela sur leur doc).

Ce que je ne comprends pas : 

1. Les autres entités sont ajoutées en background.add, et, sans index z, sont sous les décors
2. Ajouter l'objet player en background.add le fait disparaître, si on l'appelle entre les sols et les décors, alors que l'ajouter après les sols et les décors nous fait retourner au status quo...

Option envisagée : séparer plus fortement l'apparition du terrain, à savoir d'abord le sol, ensuite le player, ensuite les entités, ensuite les décors, mais j'ai peur que ça alourdisse le jeu en terme de perf.

C'est vraiment embêtant que Kaboom ait supprimé les layers... @ipante, une idée ?

**Comment by florian-rieder** [comment]
J'ai trouvé une solution: effectivement, pour que z() fonctionne, il semble qu'il faille que tous les objets soient enfants du même objet. J'ai déplacé player comme enfant de background. A ce moment là, le problème est que le joueur n'est plus au bon endroit ! Comme le player ne bougeait pas et que sa position était en coordonnées globales, il était hors de l'écran. Pour résoudre ça, j'ai ajouté un onUpdate au player, qui le déplace chaque frame au même endroit sur l'écran ! C'est un peu _hacky_, mais au moins ça marche !
