### ISSUE TITLE
Animation de mouton qui vacille à l'impact

### ISSUE THREAD

**Issue by ipante** [AnteJR/UNIL-GameJam#14]
Pour éviter l'effet "mouton qui clignote en cas de contact" qui peut échapper à un public qui n'a pas de grammaire ludique, l'idéal serait de voir le vélo partir légèrement en torche (coup de guidon à gauche, à droite, à droite, puis à gauche) avant de retrouver sa position initiale. Couplé à un son de mouton effrayé, on comprend qu'une récupération de colis est impossible en étant aussi instable. En plus, cela permettrait de voir, de manière fugace, le personnage principal sous un autre angle.

A noter : dans ce cas, il faudra bien faire attention à ne pas avoir des oscillations trop importantes pour éviter des collisions en cascade, ou à les désactiver.

Pour Mélissa, si elle a le temps et trouve l'idée bonne.

**Comment by AnteJR** [comment]
Intégrée dans mon dernier commit. Je te laisse cherck et clore cette issue si c'est ok pour toi.
