### ISSUE TITLE
Width limit pour ordinateur

### ISSUE THREAD

**Issue by astonedf** [AnteJR/UNIL-GameJam#16]
Il faudrait quand même limiter le scale sur ordi sinon on ne voit pas assez loin comme ça devient un écran horizontal. Je pense que le carré pourrait être la limite (à tester)
![Screen Shot 2023-10-10 at 08 48 22](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/49afc9b5-82d0-4b7e-b204-b27d8ac9a052)
![Screen Shot 2023-10-10 at 08 48 36](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/8aa94b49-3e62-4e3e-9839-1aeac7a0f981)

**Comment by AnteJR** [comment]
À mon avis le + simple serait de limite à genre 7-8 la constante "proportion" et ajouter un background pour les bandes de côté (on peut imaginer une version pixel art d'un BG UNIL, en bleu avec les petits dessins)

**Comment by AnteJR** [comment]
J'ai mis en prod des tests pour ça. On a 2 solutions : 

1. Laisser tel quel, et ajouter un background générique (genre bleu UNIL avec des petits dessins)
2. Resize le canvas en fonction de la proportion. Maintenant, le problème avec cette solution est que, du moins sur Kaboom 2000, on ne peut pas déplacer le canvas au centre de la page, sinon ça décale les hitbox et rend le jeu injouable. À voir si c'est changé dans Kaboom 3000, si on veut partir là-dessus.

**Comment by AnteJR** [comment]
Je vous laisse me redire en testant si vous rencontrez des problèmes sur desktop/téléphone, et ce que vous changeriez.

**Comment by AnteJR** [comment]
Pour le moment on a un background générique. Pour moi c'est OK, à voir si on édite un background spécifique, ou si on met une couleur unie style bleu UNIL.

**Comment by astonedf** [comment]
![Screen Shot 2023-10-12 at 08 52 25](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/fe1ee136-994f-4e50-ae57-adcc57fca5e0)
![Screen Shot 2023-10-12 at 08 54 15](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/421085b4-4b95-4b1d-a39e-9d91dc755398)
Chez moi ça ressemble à ça et la vision est encore trop limitée sur ordi plein écran, il faudrait que ça soit plus carré ou même plus vertical et il faut que la barre de vitesse soit dans l'écran de jeu

**Comment by florian-rieder** [comment]
J'ai une solution qui semble bien marcher, dans la quelle on donne un ratio maximal pour la taille du canvas, on le dimensionne au départ selon ce ratio maximal si le ratio de l'écran est trop grand, et on centre le canvas et on ajoute un background en CSS. On peut même utiliser une ou plusieurs images pour le fond en CSS.
