### ISSUE TITLE
Conditions de fin

### ISSUE THREAD

**Issue by AnteJR** [AnteJR/UNIL-GameJam#19]
Une fois que la zone finale, la "ligne d'arrivée" dessinée par Mélissa sera prête, il faut paramétrer des conditions de fin. J'imaginais un ralentissement du mouton sur les derniers mètres, avant de s'arrêter, et au bout de qq seconde, switcher à l'écran de fin. En lien avec l'issue #11 vu que ça fait partie intégrante du game design/feel.

**Comment by astonedf** [comment]
Merci, je regarde tout ça demain!

**Comment by AnteJR** [comment]
Pour le moment la condition de fin est : l'objet background est arrivé au bout de la longueur totale du terrain (ce qui est généralement avant la fin, selon les proportions qu'on a, vu que ça calcule le bas de l'objet background, pas le haut de la dernière texture)

**Comment by AnteJR** [comment]
J'aime beaucoup comment la fin se présente, mais 8 sec d'attente me paraît trop long. En tout cas les 3 fois où j'y suis arrivé, j'ai commencé à croire que l'app avait planté haha

**Comment by loiccattani** [comment]
Oh oui c'est cool !

Bon 8 sec ça va, partant qu'on aura une musique de fin, des confetti peut être (?) et une transition sur l'écran de fin ?

**Comment by astonedf** [comment]
Ben à voir comment les gens réagissent mais je trouve dommage si t’as pas le temps d’admirer la scene

**Comment by loiccattani** [comment]
Est-ce que la solution serait:
- d'avoir un bouton en forme de flèche en bas de l'écran (dès le début du jeu)
- qui pulse lentement tant qu'on ne clique/touche pas l'écran
- ce bouton réapparaîtrait après quelques secondes sur l'écran de fin (au même endroit, en bas de l'écran, même comportement: pulsation)
- et tant que le joueur ne presse pas longuement (l'équivalent de monter la barre de vitesse jusqu'en haut), l'écran final n'apparaîtrait pas.
?

**Comment by AnteJR** [comment]
C'est vrai que j'y suis arrivé sans musique ni genre confetti ou autres !
