### ISSUE TITLE
Game Design : perte d'une lettre en cas de contact

### ISSUE THREAD

**Issue by ipante** [AnteJR/UNIL-GameJam#20]
Pour amplifier le côté "Skills", je suggérerais de "perdre une lettre" au contact d'un obstacle.
Seul risque (en est-ce vraiment un ?) : celui de ne livre aucun voeu à la fin du jeu.
Cela pourrait appeler une fin alternative.

Qu'en penses-tu @astonedf  ?

**Comment by astonedf** [comment]
Non, ça sera trop dur comme ça :/, à l'inverse, je serais même pour mettre des lettres impossible à rater. Quand je parle du skill c'est surtout parce que pour l'instant c'est les entités qui m'évitent et pas moi qui évite les entités (et l'expérience change pas mal sur mobile et ordi)

**Comment by ipante** [comment]
Tout à fait d'accord pour les entités qui évitent.

**Comment by AnteJR** [comment]
Je pense également que de rajouter de la difficulté n'est de loin pas la priorité à avoir. Le but reste de faire un truc pour des milliers de personnes, dont probablement pas mal de non-joueur.euse.s, après tout.
