### ISSUE TITLE
Lettres coupée (textes)

### ISSUE THREAD

**Issue by astonedf** [AnteJR/UNIL-GameJam#21]
![EF9F029B-D942-40FD-B773-2AECD370839F](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/f89eae16-6e16-4c77-8940-b1b7ead7414a)
![337ED43F-A982-477F-B981-EADFA009858C](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/522383a5-555e-44f9-8c00-dfad16968fb3)

**Comment by AnteJR** [comment]
Euh chelou, je vais voir pourquoi c'est le cas (maybe du line-spacing ?)

**Comment by AnteJR** [comment]
... c'est pas du line spacing apparemment ._.

**Comment by AnteJR** [comment]
J'ai manuellement ajouté des textes à l'écran d'accueil (IE: le les ai écris à la main sur Aseprite et ils sont ajoutés en tant que sprite) pour voir ce que ça donnait.

C'est de loin pas idéal, mais je ne comprends pas vraiment d'où viennent les coupures dans les textes à la base. Peut-être est-ce Kaboom qui bug selon la size du text ? Je continue d'investiguer.

**Comment by AnteJR** [comment]
J'ai refait les textes @astonedf est-ce que tu peux tester si ils se coupent toujours ?

**Comment by AnteJR** [comment]
En tout cas en testant sur mon téléphone, les textes sont OK.

**Comment by astonedf** [comment]
Il y a rien qui va sur mon natel haha (iPhone 7s)
![24D4B5A7-D609-4657-BDC9-EB5B68781C77](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/b67d80db-dff0-4261-82ce-85441b7cd8c3)

**Comment by AnteJR** [comment]
._.

Est-ce que tu arrives à tester de ton côté si changer le lineSpacing aide sur ton iPhone ?

**Comment by astonedf** [comment]
Ouais je vais tester! Sinon, une solution facile serait de tout mettre en majuscule

**Comment by AnteJR** [comment]
> une solution facile serait de tout mettre en majuscule

On peut faire ça si vraiment, oui

**Comment by astonedf** [comment]
Le linespacing fonctionne mais n'affiche pas les lettres coupées ;(

**Comment by AnteJR** [comment]
J'avais fait un test sur mon ordinateur, et l'attribut lineSpacing espaçait mes lignes, si mes souvenirs sont bons.

Dans la doc, je ne vois que ça : 

> lineSpacing: number. The gap between each line.

**Comment by astonedf** [comment]
Ça fonctionne mieux avec une autre font
![2CA20356-9FCD-4E7E-9BA5-1BC7BB08C7AF](https://github.com/AnteJR/UNIL-GameJam/assets/34299252/dd646e40-f497-4642-ab36-dd57c452b075)

**Comment by astonedf** [comment]
Fixed mais hésite pas à changer la font si tu trouves mieux (et qu'elle marche)

**Comment by AnteJR** [comment]
Je verrai, en tout cas vu que ça semble être broken sur ton tél, il faudra que tu testes si je change la police ^^ Je te redis, et en attendant je propose de fermer l'issue, quitte à en rouvrir une pour la police plus tard.
