### ISSUE TITLE
Personnage actif dans la séquence finale

### ISSUE THREAD

**Issue by ipante** [AnteJR/UNIL-GameJam#23]
Durant la fête, il est encore possible d'appuyer sur le bouton. Cela active la sonnette (sympa) mais aussi le son d'accélération (moi sympa). Il faudrait soit bloquer toute interaction, soit veiller à ne garder que la sonnette dans ce cas.

**Comment by florian-rieder** [comment]
J'ai laissé le son de la sonnette, mais c'est facile de désactiver toute interaction après la fin de la partie, si besoin.
