### ISSUE TITLE
Scene de départ

### ISSUE THREAD

**Issue by AnteJR** [AnteJR/UNIL-GameJam#5]
Avoir un écran de départ. On part sur une sélection de langue, avec un drapeau FR et un drapeau UK.

Quand on clique sur un drapeau, la langue associée est sélectionnée, et le jeu est lancé tout de suite (avec la fonctionnalité d'attente d'input du user de l'issue #3 !)

Je me suis porté volontaire pour le faire.

**Comment by astonedf** [comment]
Il y a aussi les textes d'intro à côté des drapeaux:
-Aide Sheepy à collecter des cartes de voeux
-Help Sheepy collect holiday greetings cards

**Comment by AnteJR** [comment]
Je vais m'atteler à la scene() de départ, notamment dans son style. Les étapes qui restent selon moi : 

1. Avoir un background ;
2. Avoir de plus jolis boutons pour la sélection de langue ;
3. Avoir les textes ;
4. S'assurer de la mise en page sur téléphone et sur desktop.

**Comment by AnteJR** [comment]
Avancement de la scene() de départ : on a de bien plus jolis boutons !

**Comment by AnteJR** [comment]
Avancement de la scene() de départ : on a des textes !

Je vais travailler à un background.
